# Generated by Django 4.0.5 on 2023-09-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_create_post_localizaition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='localization',
        ),
    ]
